server:
  port: 8081

spring:
  data:
    redis:
      port: 6379
      database: 0
      host: 127.0.0.1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop-cloud?serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  mybatis-plus:
    configuration: #sql日志
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      mapper-locations: classpath:classpath:com/shop/order/dal/mapper/*.xml

  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos

    openfeign:
      httpclient:
        connection-timeout: 60000
        ReadTimeout: 60000


  application:
    name: shop-order-service

shop:
  info:
    version: 1.0.0
    base-package: com.shop.order

xxl:
  job:
    executor:
      appname: ${spring.application.name} # 执行器 AppName
      logpath: ${user.home}/logs/xxl-job/${spring.application.name} # 执行器运行日志文件存储磁盘路径
      port: 8099
    accessToken: default_token # 执行器通讯TOKEN
    admin:
      addresses: http://127.0.0.1:8000/xxl-job-admin # 调度中心部署跟地址
