server:
  port: 8081

spring:
  application:
    name: shop-order-service

  data:
    redis:
      port: 6379
      database: 0
      host: 127.0.0.1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop-cloud?serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  mybatis-plus:
    configuration: #sql日志
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      mapper-locations: classpath:classpath:com/shop/order/dal/mapper/*.xml

  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos


    openfeign:
      httpclient:
        connection-timeout: 60000
        ReadTimeout: 60000

    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:7070 # Sentinel 控制台地址
        port: 8720
      datasource:
        ds1:
          # 对应 DataSourcePropertiesConfiguration 类
          nacos:
            server-addr: 127.0.0.1:8848 # Nacos 服务器地址
            namespace: # Nacos 命名空间
            group_id: DEFAULT_GROUP # Nacos 分组
            data_id: ${spring.application.name}-flow-rule # Nacos 配置集编号
            data_type: json # 数据格式
            rule-type: FLOW # 规则类型
            username: nacos
            password: nacos

feign:
  sentinel:
    enabled: true # 开启 Sentinel 对 Feign 的支持，默认为 false 关闭。

shop:
  info:
    version: 1.0.0
    base-package: com.shop.order

xxl:
  job:
    executor:
      appname: ${spring.application.name} # 执行器 AppName
      logpath: ${user.home}/logs/xxl-job/${spring.application.name} # 执行器运行日志文件存储磁盘路径
      port: 8099
    accessToken: default_token # 执行器通讯TOKEN
    admin:
      addresses: http://127.0.0.1:8000/xxl-job-admin # 调度中心部署跟地址
