spring:
  application:
    name: shop-pay-service

  data:
    redis:
      port: 6379
      database: 0
      host: 127.0.0.1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop-cloud?serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos

    openfeign:
      httpclient:
        connection-timeout: 60000
        ReadTimeout: 60000

    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      transport:
        port: 8731
        dashboard: 127.0.0.1:7070 # Sentinel 控制台地址

feign:
  sentinel:
    enabled: true # 开启 Sentinel 对 Feign 的支持，默认为 false 关闭。

server:
  port: 8082

shop:
  info:
    version: 1.0.0
    base-package: com.shop.pay

xxl:
  job:
    executor:
      appname: ${spring.application.name} # 执行器 AppName
      logpath: ${user.home}/logs/xxl-job/${spring.application.name} # 执行器运行日志文件存储磁盘路径
      port: 8099
    accessToken: default_token # 执行器通讯TOKEN
    admin:
      addresses: http://127.0.0.1:8000/xxl-job-admin # 调度中心部署跟地址
